/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-08-18 04:30:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class snsTerm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1597301381698L));
    _jspx_dependants.put("jar:file:/C:/APP/eGovFrameDev-3.9.0-64bit/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final-project/WEB-INF/lib/spring-webmvc-4.3.28.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1595281502000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.28.RELEASE.jar", Long.valueOf(1597301370702L));
    _jspx_dependants.put("jar:file:/C:/APP/eGovFrameDev-3.9.0-64bit/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final-project/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/views/user/../common/navi.jsp", Long.valueOf(1597717822325L));
    _jspx_dependants.put("/WEB-INF/views/common/tags.jsp", Long.valueOf(1597717822327L));
    _jspx_dependants.put("jar:file:/C:/APP/eGovFrameDev-3.9.0-64bit/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final-project/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/APP/eGovFrameDev-3.9.0-64bit/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final-project/WEB-INF/lib/spring-webmvc-4.3.28.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1595281502000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("<title>같이 보자! 공공연한사이</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/jquery.fullPage.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/style.css\" />\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/jquery.color.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/custom.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"header\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<nav class=\"navbar sticky-top transparent custom-color\" id=\"navbar-top\">\n");
      out.write("\t\t\t<!-- side navi bar btn -->\n");
      out.write("\t\t\t<div class=\"col-1\">\n");
      out.write("\t\t\t\t<button id=\"sidebarCollapse\" class=\"btn navbar-toggler\"\n");
      out.write("\t\t\t\t\ttype=\"button\" data-toggle=\"collapse\">\n");
      out.write("\t\t\t\t\t<div id=\"sidenav-icon\">\n");
      out.write("\t\t\t\t\t\t<span></span> <span></span> <span></span> <span></span> <span></span>\n");
      out.write("\t\t\t\t\t\t<span></span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- side navi bar btn -->\n");
      out.write("\t\t\t<!-- brand name, title -->\n");
      out.write("\t\t\t<div class=\"col-3 text-left\">\n");
      out.write("\t\t\t\t<a class=\"navbar-brand font-weight-bolder\" href=\"/home.do\"> <span\n");
      out.write("\t\t\t\t\tclass=\"h2 font-weight-bolder custom-color\">공공연한사이</span>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- brand name, title -->\n");
      out.write("\t\t\t<!-- search bar -->\n");
      out.write("\t\t\t<div class=\"col-4\">\n");
      out.write("\t\t\t\t<form class=\"form-inline mr-sm-2 searchform\">\n");
      out.write("\t\t\t\t\t<input type=\"search\" class=\"form-control\" id=\"search-box\" />\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"btn\" type=\"button\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-search fa-2x custom-color\"></i>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- search bar -->\n");
      out.write("\t\t\t<!-- user icons -->\n");
      out.write("\t\t\t<div class=\"col-4 text-right\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- user icons -->\n");
      out.write("\t\t</nav>\n");
      out.write("\t\t<!-- Vertical navbar -->\n");
      out.write("\t\t<nav class=\"vertical-nav active\" id=\"sidebar\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-12 sidebar-top\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<ul class=\"nav flex-column m-3\">\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\">\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled components mb-5\">\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"#homeSubmenu\"\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"collapse\" aria-expanded=\"false\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"dropdown-toggle h4\">공연예매</a>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"collapse list-unstyled\" id=\"homeSubmenu\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/performance/list.do\" class=\"h6\">콘서트</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"h6\">뮤지컬</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"h6\">연극</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"h4\">메이트</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"h4\">뒤풀이</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"h4\">이벤트</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/qna/list.do\" class=\"h4\">고객문의센터</a></li>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"h4\">마이페이지</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</nav>\n");
      out.write("\t\t<!-- End vertical navbar -->\n");
      out.write(" ");
      out.write("\n");
      out.write("</div>\n");
      out.write("<div class=\"container \" style=\"margin-top: 150px;\">\n");
      out.write("\t<div class=\"row \">\n");
      out.write("\t\t<div class=\"col-8 mx-auto\" >\n");
      out.write("\t\t\t<form name=\"term\" id=\"term-form\" method=\"get\" action=\"snsSignup.do\" onSubmit=\"return CheckForm(this)\">\n");
      out.write("\t\t\t\t<div class=\"card border-0\">\n");
      out.write("\t\t\t\t\t<div class=\"card-header bg-white text-black font-weight-bolder card border-0 mb-3 \"><h4>공공연한사이 SNS약관동의</h4></div>\n");
      out.write("\t\t\t\t\t<div >\n");
      out.write("\t\t\t\t\t<table class=\"table\">\n");
      out.write("\t\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"padding-bottom: 0px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-0\" style=\"padding-left: 0\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"chk\" id=\"chkAll\" style=\"margin-right: 15px; margin-top: 6px;\"/> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-9\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5><strong>공공연한사이 전체약관에 동의합니다.</strong></h5>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"table-secondary\">\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"padding-bottom: 0px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-row\">\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"chk\" name=\"chk\" id=\"chk2\" style=\"margin-right: 15px; margin-top: 6px;\" /> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-9\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>공공연한사이 이용약관 동의(필수)</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-2\" style=\"margin-left: 20px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button id=\"spreadBtn1\" type=\"button\" class=\"btn btn-secondary\">전문보기</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"hiddenContent1\" style=\"display: none ;\"><small>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제 1장 총 칙\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제1조(목적)</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t이 약관은 공공연한사이 주식회사가 운영하는 인터넷사이트(http://www.gongsa.com) 에서 제공하는 전자상거래 관련 서비스를 이용함에 있어 회사와 이용자의 권리,</br> 의무, 책임사항 및 서비스 이용절차 등에 관한 사항을 규정함을 목적으로 합니다. 회사가 운영하는 오프라인의 영업장과 관련된 전자상거래 관련 서비스에 대해서도 그 성질에 반하지 아니하는 한 이 약관을 준용합니다.</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제2조(용어의 정의)</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t① 이 약관에서 사용하는 용어의 정의는 다음과 같습니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t1. 회사 : 예스이십사 주식회사를 의미하며, 이와 아울러 예스이십사 주식회사가 재화 또는 용역(이하 ‘재화 등’이라 합니다)을 이용자에게 제공하기 위하여 컴퓨터 등 </br>정보통신설비를 이용하여 재화 등을 거래할 수 있도록 설정한 가상의 영업장(www.yes24.com)을 말하고, 또한 사이버 몰을 운영하는 사업자의 의미로도 사용합니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t2. 이용자 : 이 약관에 따라 회사가 제공하는 서비스를 받는 회원 및 비회원을 말합니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t3. 회원 : 회사에 개인정보를 제공하여 회원등록을 한 자, 회사가 제공하는 서비스를 계속적으로 이용할 수 있는 자로서 아래와 같이 구분될 수 있습니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t라.외국인회원 : 외국인등록번호로 가입한 회원\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t마.해외거주회원 : 해외거주 주소로 가입한 회원</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t3. 취소의 시점이 관람일 1일 전 ~ 9일 전인 경우 아래 기준의 취소수수료를 부과합니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t 관람일 6일 전 ~ 관람일 3일 전까지 : 티켓 금액의 20%\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t 관람일 2일 전 ~ 관람일 1일 전까지 : 티켓 금액의 30%\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t 단, 예매 후 7일 이내라도 취소시점이 관람일로부터 10일 이내라면 그에 해당하는 취소수수료가 부과됩니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t⑥ 구매자가 예매 티켓을 분실, 훼손한 경우 회사는 해당 예매 취소 및 변경, 재발행을 허용하지 않을 수 있습니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t결제 방법에 따라 취소 절차가 다르게 적용될 수 있습니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t1. 신용카드 결제\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t예매 취소 시 카드사의 부분취소 방식에 따라 기존 결제내역을 전체 취소하고 취소 시점에 따라 취소수수료와 예매수수료 또는 배송료를 재승인합니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t2. 무통장 입금 결제\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t회사는 회원이 기재한 환불 계좌 정보(은행 계좌번호와 예금주 등)로 취소 수수료 등 기타 비용을 공제한 금액을 회원 환불 계좌에 입금합니다.\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t3. 자신의 애드온 박스나 리뷰를 통해서 자가 구매를 하는 경우\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제2조(연결\"몰\"과 피연결\"몰\" 간의 관계)</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t이 약관에 명시하지 않은 사항은 관련법령과 회사의 규정 및 기타 상관례에 따릅니다.</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t부칙\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제1조 (시행일자)\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t본 약관은 2020년 03월 10일부터 시행합니다.</small>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"table-secondary\">\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"padding-bottom: 0px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-row\">\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"chk\" name=\"chk\" id=\"chk2\" style=\"margin-right: 15px; margin-top: 6px;\" /> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-9\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>개인정보 수집 및 이용 동의(필수)</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-2\" style=\"margin-left: 20px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button id=\"spreadBtn2\" type=\"button\" class=\"btn btn-secondary\">전문보기</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"hiddenContent2\" style=\"display: none ;\"><small>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제 1장 총 칙\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제1조(목적)</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t이 약관은 공공연한사이 주식회사가 운영하는 인터넷사이트(http://www.gongsa.com) 에서 제공하는 전자상거래 관련 서비스를 이용함에 있어 회사와 이용자의 권리,</br> 의무, 책임사항 및 서비스 이용절차 등에 관한 사항을 규정함을 목적으로 합니다. 회사가 운영하는 오프라인의 영업장과 관련된 전자상거래 관련 서비스에 대해서도 그 성질에 반하지 아니하는 한 이 약관을 준용합니다.</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제2조(용어의 정의)</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t① 이 약관에서 사용하는 용어의 정의는 다음과 같습니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t1. 회사 : 예스이십사 주식회사를 의미하며, 이와 아울러 예스이십사 주식회사가 재화 또는 용역(이하 ‘재화 등’이라 합니다)을 이용자에게 제공하기 위하여 컴퓨터 등 </br>정보통신설비를 이용하여 재화 등을 거래할 수 있도록 설정한 가상의 영업장(www.yes24.com)을 말하고, 또한 사이버 몰을 운영하는 사업자의 의미로도 사용합니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t2. 이용자 : 이 약관에 따라 회사가 제공하는 서비스를 받는 회원 및 비회원을 말합니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t3. 회원 : 회사에 개인정보를 제공하여 회원등록을 한 자, 회사가 제공하는 서비스를 계속적으로 이용할 수 있는 자로서 아래와 같이 구분될 수 있습니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t라.외국인회원 : 외국인등록번호로 가입한 회원\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t마.해외거주회원 : 해외거주 주소로 가입한 회원</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t3. 취소의 시점이 관람일 1일 전 ~ 9일 전인 경우 아래 기준의 취소수수료를 부과합니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t 관람일 6일 전 ~ 관람일 3일 전까지 : 티켓 금액의 20%\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t 관람일 2일 전 ~ 관람일 1일 전까지 : 티켓 금액의 30%\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t 단, 예매 후 7일 이내라도 취소시점이 관람일로부터 10일 이내라면 그에 해당하는 취소수수료가 부과됩니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t⑥ 구매자가 예매 티켓을 분실, 훼손한 경우 회사는 해당 예매 취소 및 변경, 재발행을 허용하지 않을 수 있습니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t결제 방법에 따라 취소 절차가 다르게 적용될 수 있습니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t1. 신용카드 결제\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t예매 취소 시 카드사의 부분취소 방식에 따라 기존 결제내역을 전체 취소하고 취소 시점에 따라 취소수수료와 예매수수료 또는 배송료를 재승인합니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t2. 무통장 입금 결제\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t회사는 회원이 기재한 환불 계좌 정보(은행 계좌번호와 예금주 등)로 취소 수수료 등 기타 비용을 공제한 금액을 회원 환불 계좌에 입금합니다.\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t3. 자신의 애드온 박스나 리뷰를 통해서 자가 구매를 하는 경우\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제2조(연결\"몰\"과 피연결\"몰\" 간의 관계)</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제42조(법령 및 준용)\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t이 약관에 명시하지 않은 사항은 관련법령과 회사의 규정 및 기타 상관례에 따릅니다.</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t부칙\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제1조 (시행일자)\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t본 약관은 2020년 03월 10일부터 시행합니다.</small>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"table-secondary\">\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"padding-bottom: 0px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-row\">\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"chk\" name=\"chk\" id=\"chk2\" style=\"margin-right: 15px; margin-top: 6px;\" /> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-9\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>개인정보 취급 위탁 동의(필수)</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-2\" style=\"margin-left: 20px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button id=\"spreadBtn3\" type=\"button\" class=\"btn btn-secondary\">전문보기</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"hiddenContent3\" style=\"display: none ;\"><small>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제 1장 총 칙\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제1조(목적)</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t이 약관은 공공연한사이 주식회사가 운영하는 인터넷사이트(http://www.gongsa.com) 에서 제공하는 전자상거래 관련 서비스를 이용함에 있어 회사와 이용자의 권리,</br> 의무, 책임사항 및 서비스 이용절차 등에 관한 사항을 규정함을 목적으로 합니다. 회사가 운영하는 오프라인의 영업장과 관련된 전자상거래 관련 서비스에 대해서도 그 성질에 반하지 아니하는 한 이 약관을 준용합니다.</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제2조(용어의 정의)</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t① 이 약관에서 사용하는 용어의 정의는 다음과 같습니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t1. 회사 : 예스이십사 주식회사를 의미하며, 이와 아울러 예스이십사 주식회사가 재화 또는 용역(이하 ‘재화 등’이라 합니다)을 이용자에게 제공하기 위하여 컴퓨터 등 </br>정보통신설비를 이용하여 재화 등을 거래할 수 있도록 설정한 가상의 영업장(www.yes24.com)을 말하고, 또한 사이버 몰을 운영하는 사업자의 의미로도 사용합니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t2. 이용자 : 이 약관에 따라 회사가 제공하는 서비스를 받는 회원 및 비회원을 말합니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t3. 회원 : 회사에 개인정보를 제공하여 회원등록을 한 자, 회사가 제공하는 서비스를 계속적으로 이용할 수 있는 자로서 아래와 같이 구분될 수 있습니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t라.외국인회원 : 외국인등록번호로 가입한 회원\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t마.해외거주회원 : 해외거주 주소로 가입한 회원</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t3. 취소의 시점이 관람일 1일 전 ~ 9일 전인 경우 아래 기준의 취소수수료를 부과합니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t 관람일 6일 전 ~ 관람일 3일 전까지 : 티켓 금액의 20%\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t 관람일 2일 전 ~ 관람일 1일 전까지 : 티켓 금액의 30%\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t 단, 예매 후 7일 이내라도 취소시점이 관람일로부터 10일 이내라면 그에 해당하는 취소수수료가 부과됩니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t⑥ 구매자가 예매 티켓을 분실, 훼손한 경우 회사는 해당 예매 취소 및 변경, 재발행을 허용하지 않을 수 있습니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t결제 방법에 따라 취소 절차가 다르게 적용될 수 있습니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t1. 신용카드 결제\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t예매 취소 시 카드사의 부분취소 방식에 따라 기존 결제내역을 전체 취소하고 취소 시점에 따라 취소수수료와 예매수수료 또는 배송료를 재승인합니다.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t2. 무통장 입금 결제\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t회사는 회원이 기재한 환불 계좌 정보(은행 계좌번호와 예금주 등)로 취소 수수료 등 기타 비용을 공제한 금액을 회원 환불 계좌에 입금합니다.\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t3. 자신의 애드온 박스나 리뷰를 통해서 자가 구매를 하는 경우\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제2조(연결\"몰\"과 피연결\"몰\" 간의 관계)</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제42조(법령 및 준용)\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t이 약관에 명시하지 않은 사항은 관련법령과 회사의 규정 및 기타 상관례에 따릅니다.</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t부칙\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t제1조 (시행일자)\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t본 약관은 2020년 03월 10일부터 시행합니다.</small>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group col-md-12 text-center mt-4\">\n");
      out.write("\t   \t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary btn-lg\" >동의 후 회원가입</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/jquery/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("// 체크박스 전체선택 및 전체 해제\n");
      out.write("$(\"#chkAll\").click(function(){\n");
      out.write("\tif($(\"#chkAll\").is(\":checked\")){\n");
      out.write("\t\t$(\".chk\").prop(\"checked\", true);\n");
      out.write("\t}\n");
      out.write("\telse{\n");
      out.write("\t\t$(\".chk\").prop(\"checked\", false);\n");
      out.write("\t}\n");
      out.write("});\n");
      out.write("\n");
      out.write("// 한개의 체크박스 선택 해제시 전체 선택 체크박스도 해제\n");
      out.write("$(\".chk\").click(function(){\n");
      out.write("\tif($(\"input[name='chk']:checked\").length == 3) {\n");
      out.write("\t\t$(\"#chkAll\").prop(\"checked\", true);\n");
      out.write("\t}else{\n");
      out.write("\t\t$(\"#chkAll\").prop(\"checked\", false);\n");
      out.write("\t}\n");
      out.write("});\n");
      out.write("\n");
      out.write("$(document).ready(function(){\n");
      out.write("\t $(\"#spreadBtn1\").click(function(){ \n");
      out.write("\t\t $(\"#hiddenContent1\").toggle()\n");
      out.write("\t\t //show() hide() toggle()\n");
      out.write("\t}); \n");
      out.write("});\n");
      out.write("$(document).ready(function(){\n");
      out.write("\t $(\"#spreadBtn2\").click(function(){ \n");
      out.write("\t\t $(\"#hiddenContent2\").toggle()\n");
      out.write("\t\t //show() hide() toggle()\n");
      out.write("\t}); \n");
      out.write("});\n");
      out.write("$(document).ready(function(){\n");
      out.write("\t $(\"#spreadBtn3\").click(function(){ \n");
      out.write("\t\t $(\"#hiddenContent3\").toggle()\n");
      out.write("\t\t //show() hide() toggle()\n");
      out.write("\t}); \n");
      out.write("});\n");
      out.write("\n");
      out.write("\n");
      out.write("function CheckForm(Join){\n");
      out.write("    \n");
      out.write("    var chkAll=document.term.chkAll.checked;\n");
      out.write("    \n");
      out.write("    if(!chkAll){\n");
      out.write("        alert('약관에 모두 동의해 주세요');\n");
      out.write("        return false;\n");
      out.write("    } \n");
      out.write("    \treturn \n");
      out.write("  \n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/user/../common/navi.jsp(37,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty LOGIN_USER}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<a href=\"/signin.do\" class=\"btn\" type=\"button\">\n");
          out.write("\t\t\t\t\t\t<i class=\"fas fa-sign-in-alt fa-2x custom-color\"></i>\n");
          out.write("\t\t\t\t\t</a>\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<a class=\"btn\" href=\"/mypage/mypagemain.do\">\n");
          out.write("\t\t\t\t\t\t<i class=\"far fa-user fa-2x custom-color\"></i>\n");
          out.write("\t\t\t\t\t</a>\n");
          out.write("\t\t\t\t\n");
          out.write("\t\t\t\t\t<a href=\"#\" class=\"btn\" type=\"button\">\n");
          out.write("\t\t\t\t\t\t<i class=\"far fa-bell fa-2x custom-color\"></i>\n");
          out.write("\t\t\t\t\t</a>\n");
          out.write("\t\t\t\t\t<a href=\"#\" class=\"btn\" type=\"button\">\n");
          out.write("\t\t\t\t\t\t<i class=\"far fa-envelope fa-2x custom-color\"></i>\n");
          out.write("\t\t\t\t\t</a>\n");
          out.write("\t\t\n");
          out.write("\t\t\t\t\t<a href=\"/signout.do\" class=\"btn\" type=\"button\">\n");
          out.write("\t\t\t\t\t\t<i class=\"fas fa-sign-out-alt fa-2x custom-color\"></i>\n");
          out.write("\t\t\t\t\t</a>\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
